version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:5432
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d:ro
      - db:/var/lib/postgres
  backend:
    depends_on:
      - postgresdb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $SERVICE_PORT:4000
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=5432

  frontend:
    depends_on:
      - backend
    build: ./frontend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $UI_PORT:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db:
